[package]
name = "relay"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = { version = "1.7.0", optional = true }
polling = "2.1.0"
json = "0.12.4"
chrono = "0.4.19"
byteorder = "1.4.3"
