[package]
name = "roboteq_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relay = { path = ".." }
termion = "1.5.5"
[target.'cfg(unix)'.dependencies]
socketcan = { version = "1.7.0" }
